### ISSUE TITLE
Unable to increase persistence.size

### ISSUE THREAD

**Issue by simensen** [EventStore/EventStore.Charts#27]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**:

Kubernetes: v1.10.11
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}

**Which chart**:

Repo: https://eventstore.github.io/EventStore.Charts
Chart: eventstore/eventstore

**What happened**:

When changing `persistence.size`, from `8Gi` to something else, like `32Gi`, Helm reports an error.

**What you expected to happen**:

The persistence storage increases.

**How to reproduce it** (as minimally and precisely as possible):

```
helm install -n eventstore-persistence-test eventstore/eventstore \
    --set 'persistence.enabled=true'

helm upgrade  eventstore-persistence-test eventstore/eventstore \
    --set 'persistence.size=32Gi'
```

Result should be something like:

```
UPGRADE FAILED
ROLLING BACK
Error: StatefulSet.apps "eventstore-persistence-test" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
Error: UPGRADE FAILED: StatefulSet.apps "eventstore-persistence-test" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden.
```

**Anything else we need to know**:

I'm using Helm via Terraform and the results are the same. Confirmed (as shown above) that this issue exists when using vanilla Helm.

**Comment by riccardone** [comment]
@simensen hi, I think that you can resize existing Persistent Volume Claim one by one. Here is some docs
https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/
As far as I know the upgrade command is not capable of doing volume resizing

**Comment by simensen** [comment]
@riccardone That might be true, but using Helm abstracts a lot of this. It also doesn't look like I can edit the default stores created anyway:

```
# persistentvolumeclaims "data-eventstore-0" was not valid:
# * spec: Forbidden: field is immutable after creation
```

This when changing:

```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: hostpath
  volumeName: pvc-ae7dcd41-5a6f-11e9-84ec-025000000001
```

... to

```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
  storageClassName: hostpath
  volumeName: pvc-ae7dcd41-5a6f-11e9-84ec-025000000001
```

I think the ideal solution for me would be to manage the creation of the pvc myself, but as documented in #28, I am not sure that works yet. If it does, I can't figure out how to specify the pvc for each individual eventstore pod.
