### ISSUE TITLE
Persistence existingClaim is only used by the admin pod

### ISSUE THREAD

**Issue by ghost** [EventStore/EventStore.Charts#41]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm and Tiller v2.14.2
Kubernetes 1.13.7 (AKS)

**Which chart**:
eventstore/eventstore

**What happened**:
When providing the `persistence.existingClaim` option, only the `eventstore-admin` pod seems to use the claim. The other `eventstore` pods create their own persistent volume claims. The PVC we have provided the helm chart is for Azure managed-premium disks.

We are running an EventStore with `clusterSize=3` and get the following:

![image](https://user-images.githubusercontent.com/49901762/61620231-5f7b4080-ac68-11e9-8560-78f5874eb2d7.png)

![image](https://user-images.githubusercontent.com/49901762/61620266-728e1080-ac68-11e9-9696-9aa061b406ea.png)

**What you expected to happen**:
We would expect all of the nodes to use the provided PVC and therefore create `managed-premium` Azure disks, rather than just the admin pod.

**How to reproduce it** (as minimally and precisely as possible):
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstore
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 8Gi
```

```
helm.exe upgrade --install --set persistence.enabled=true,persistence.existingClaim=eventstore,imageTag=release-5.0.1,clusterSize=3 eventstore eventstore/eventstore
```
