### ISSUE TITLE
Eventstore Behind nlb with ssl termination

### ISSUE THREAD

**Issue by itninja-hue** [EventStore/EventStore.Charts#50]
**Is this a request for help?**:

--- Help

**Version of Helm and Kubernetes**:
1.13 (eks)
**Which chart**:
stable eventstore/eventsore
**What happened**:
I set up my nlb with ssl termination, and trying to access eventstore on https via ingress
````yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eventstore-admin-ingress
  namespace: eventstore
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/websocket-services: dev-eventstore-admin

spec:
  rules:
  - host: eventstore.example.com
    http:
      paths:
      - backend:
          serviceName: dev-eventstore-admin
          servicePort: 2113
...
````
In a https context i can t enable projections :/ 
when i force ssl redirection with 
```yaml
nginx.ingress.kubernetes.io/force-ssl-redirect: "true 
```
i get into a redirection loop 

**What you expected to happen**:
connect to eventstore with https with ingress

**How to reproduce it** (as minimally and precisely as possible):
Use the manifest files

**Anything else we need to know**:
